import Head from "next/head"
import { Button } from "@joinhandshake/ui-components"

export default function Home() {
  return (
    <>
      <Head>
        <title>Handshake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto pt-10">
        <h1 className="text-4xl font-bold">Testing only!</h1>
        <p className="text-lg">
          These button colors are NOT legit at all. Don&apos;t use them when
          building components. Just for testing things right now.
        </p>
        <Button variant="primary">primary button!</Button>
        <Button variant="secondary">secondary button!</Button>
      </main>
    </>
  )
}
