import Head from "next/head"
import { ExampleButton } from "../components/examples"

export default function Home() {
  return (
    <>
      <Head>
        <title>Handshake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto pt-10">
        <h1 className="text-4xl font-bold">Testing only!</h1>
        <p className="text-lg">
          These button colors are NOT legit at all. Don&apos;t use them when
          building components. Just for testing things right now.
        </p>
        <ExampleButton variant="primary">primary button!</ExampleButton>
        <ExampleButton variant="secondary">secondary button!</ExampleButton>
      </main>
    </>
  )
}
