# Prevents Netlify optimization as already performed by NextJS  
# Netlify recommends disabling
[build.processing]
  skip_processing = true

# Use yarn instead of NPM
[build.environment]
  NETLIFY_USE_YARN = 'true'
